name: angel_sqljocky
version: 1.0.0-dev+1
description: SQL-enabled services for the Angel framework. Works well with Furlong.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/angel-dart/angel_sqljocky
dependencies:
  angel_framework: ">=1.0.0-dev < 2.0.0"
  furlong: ">=1.0.0-dev <2.0.0"
  json_god: ">=2.0.0-beta <3.0.0"
  sqljocky: ">=0.14.1 <0.15.0"
dev_dependencies:
  http: ">= 0.11.3 < 0.12.0"
  test: ">= 0.12.13 < 0.13.0"